[tool.poetry]
name = "typedtsv"
version = "0.6.0"
description = ""
authors = ["James Lee <jimmybot@jimmybot.com>"]

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
toml = "^0.9.4"
